apiVersion : apps/v1
kind: Deployment
metadata:
  name: apitemperaturak8s 
spec:
  replicas: 4
  selector:
    matchLabels:
      app: apitemperaturak8s
  template:
    metadata:
      labels:
        app: apitemperaturak8s
    spec:
      containers:
        - name: apitemperaturak8s
          image: groffegithubactions.azurecr.io/apitemperaturak8s
          ports:
          - containerPort: 80